baseurl = "https://socialcopsdev.github.io/hugo-starter/"
title = "Hugo Starter Project"
languageCode = "en-us"
canonifyurls = true

[[menu.main]]
    name = "Product Page 1"
    weight = -110
    identifier = "Product Page 1"
    url = "/product/sampleproduct1/"
[[menu.main]]
    name = "Product Page 2"
    weight = -100
    url = "/product/sampleproduct2/"
